# Makefiles are used to automate the build process of a project.
# they are also contextual memory aids for the developer.
# This makefile is used to build the project and run tests.
# It is also used to build the documentation

# This is the default target. It is run when you type 'make' in the terminal
# It is used to build the project
all: build

# This target is used to build the project
build:
	@echo "Building the project"
	nimble build
	@echo "Done"
